/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.school;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author Taha Rasheed
 */
public class addResultSubjects extends javax.swing.JFrame {

    /**
     * Creates new form weeklyResultFrame
     */
    public addResultSubjects() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        getClass = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        subject1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        marks1 = new javax.swing.JTextField();
        addResult = new javax.swing.JButton();
        getRollNo = new javax.swing.JTextField();
        rollNo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        oMarks = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        getTest = new javax.swing.JTextField();
        oMarks1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        marks2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        subject2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        oMarks2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        marks3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        subject3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        oMarks3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        marks4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        subject4 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        oMarks4 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        marks5 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        subject5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        oMarks5 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        marks6 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        subject6 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        oMarks6 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        marks7 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        subject7 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        oMarks7 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        marks8 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        subject8 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        oMarks8 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        marks9 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        subject9 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        oMarks9 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        marks10 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        subject10 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        resultId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(206, 212, 218));
        jPanel3.setPreferredSize(new java.awt.Dimension(648, 513));

        getClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Nursery", "Prep", "Class 1", "Class 2", "Class 3", "Class 4", "Class 5", "Class 6", "Class 7", "Class 8", "Class 9", "Class 10" }));
        getClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getClassActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(33, 37, 41));
        jLabel13.setText("Subject");

        subject1.setBackground(new java.awt.Color(248, 249, 250));
        subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(33, 37, 41));
        jLabel16.setText("Class");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(33, 37, 41));
        jLabel17.setText("Total Marks");

        marks1.setBackground(new java.awt.Color(248, 249, 250));
        marks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks1ActionPerformed(evt);
            }
        });

        addResult.setBackground(new java.awt.Color(28, 126, 214));
        addResult.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addResult.setForeground(new java.awt.Color(33, 37, 41));
        addResult.setText("Add Result");
        addResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addResultMouseClicked(evt);
            }
        });
        addResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResultActionPerformed(evt);
            }
        });

        getRollNo.setBackground(new java.awt.Color(248, 249, 250));
        getRollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRollNoActionPerformed(evt);
            }
        });

        rollNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rollNo.setForeground(new java.awt.Color(33, 37, 41));
        rollNo.setText("Roll No");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(33, 37, 41));
        jLabel19.setText("Obtained Marks");

        oMarks.setBackground(new java.awt.Color(248, 249, 250));
        oMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarksActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(33, 37, 41));
        jLabel20.setText("Test Type");

        getTest.setBackground(new java.awt.Color(248, 249, 250));
        getTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTestActionPerformed(evt);
            }
        });

        oMarks1.setBackground(new java.awt.Color(248, 249, 250));
        oMarks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarks1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(33, 37, 41));
        jLabel21.setText("Obtained Marks");

        marks2.setBackground(new java.awt.Color(248, 249, 250));
        marks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(33, 37, 41));
        jLabel22.setText("Total Marks");

        subject2.setBackground(new java.awt.Color(248, 249, 250));
        subject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(33, 37, 41));
        jLabel14.setText("Subject");

        oMarks2.setBackground(new java.awt.Color(248, 249, 250));
        oMarks2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarks2ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(33, 37, 41));
        jLabel23.setText("Obtained Marks");

        marks3.setBackground(new java.awt.Color(248, 249, 250));
        marks3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks3ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(33, 37, 41));
        jLabel24.setText("Total Marks");

        subject3.setBackground(new java.awt.Color(248, 249, 250));
        subject3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(33, 37, 41));
        jLabel15.setText("Subject");

        oMarks3.setBackground(new java.awt.Color(248, 249, 250));
        oMarks3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarks3ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(33, 37, 41));
        jLabel25.setText("Obtained Marks");

        marks4.setBackground(new java.awt.Color(248, 249, 250));
        marks4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks4ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(33, 37, 41));
        jLabel26.setText("Total Marks");

        subject4.setBackground(new java.awt.Color(248, 249, 250));
        subject4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject4ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(33, 37, 41));
        jLabel27.setText("Subject");

        oMarks4.setBackground(new java.awt.Color(248, 249, 250));
        oMarks4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarks4ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(33, 37, 41));
        jLabel28.setText("Obtained Marks");

        marks5.setBackground(new java.awt.Color(248, 249, 250));
        marks5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks5ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(33, 37, 41));
        jLabel29.setText("Total Marks");

        subject5.setBackground(new java.awt.Color(248, 249, 250));
        subject5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject5ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(33, 37, 41));
        jLabel30.setText("Subject");

        oMarks5.setBackground(new java.awt.Color(248, 249, 250));
        oMarks5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarks5ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(33, 37, 41));
        jLabel31.setText("Obtained Marks");

        marks6.setBackground(new java.awt.Color(248, 249, 250));
        marks6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks6ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(33, 37, 41));
        jLabel32.setText("Total Marks");

        subject6.setBackground(new java.awt.Color(248, 249, 250));
        subject6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject6ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(33, 37, 41));
        jLabel33.setText("Subject");

        oMarks6.setBackground(new java.awt.Color(248, 249, 250));
        oMarks6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarks6ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(33, 37, 41));
        jLabel34.setText("Obtained Marks");

        marks7.setBackground(new java.awt.Color(248, 249, 250));
        marks7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks7ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(33, 37, 41));
        jLabel35.setText("Total Marks");

        subject7.setBackground(new java.awt.Color(248, 249, 250));
        subject7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject7ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(33, 37, 41));
        jLabel36.setText("Subject");

        oMarks7.setBackground(new java.awt.Color(248, 249, 250));
        oMarks7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarks7ActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(33, 37, 41));
        jLabel37.setText("Obtained Marks");

        marks8.setBackground(new java.awt.Color(248, 249, 250));
        marks8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks8ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(33, 37, 41));
        jLabel38.setText("Total Marks");

        subject8.setBackground(new java.awt.Color(248, 249, 250));
        subject8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject8ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(33, 37, 41));
        jLabel39.setText("Subject");

        oMarks8.setBackground(new java.awt.Color(248, 249, 250));
        oMarks8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarks8ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(33, 37, 41));
        jLabel40.setText("Obtained Marks");

        marks9.setBackground(new java.awt.Color(248, 249, 250));
        marks9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks9ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(33, 37, 41));
        jLabel41.setText("Total Marks");

        subject9.setBackground(new java.awt.Color(248, 249, 250));
        subject9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject9ActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(33, 37, 41));
        jLabel42.setText("Subject");

        oMarks9.setBackground(new java.awt.Color(248, 249, 250));
        oMarks9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oMarks9ActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(33, 37, 41));
        jLabel43.setText("Obtained Marks");

        marks10.setBackground(new java.awt.Color(248, 249, 250));
        marks10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks10ActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(33, 37, 41));
        jLabel44.setText("Total Marks");

        subject10.setBackground(new java.awt.Color(248, 249, 250));
        subject10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject10ActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(33, 37, 41));
        jLabel45.setText("Subject");

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(33, 37, 41));
        jLabel46.setText("Result Id");

        resultId.setBackground(new java.awt.Color(248, 249, 250));
        resultId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getClass, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rollNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getRollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getTest, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addResult, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marks10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oMarks9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultId, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(rollNo)
                    .addComponent(getRollNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(getTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(resultId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(marks1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(oMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(marks2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(oMarks1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(marks3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(oMarks2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(marks4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(oMarks3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(marks5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(oMarks4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(subject6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(marks6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(oMarks5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(subject7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(marks7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(oMarks6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(subject8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(marks8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(oMarks7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(subject9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(marks9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(oMarks8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(subject10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(marks10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(oMarks9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(28, 126, 214));
        jPanel2.setForeground(new java.awt.Color(33, 37, 41));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 37, 41));
        jLabel1.setText("Add Result Subjects");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addResultActionPerformed

    private void addResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addResultMouseClicked
        // Get values from text fields and combo box
        int rollNo = Integer.parseInt(getRollNo.getText());
        int Result = Integer.parseInt(resultId.getText());
        String className = (String) getClass.getSelectedItem();
        String[] subjectNames = {
            subject1.getText(),
            subject2.getText(),
            subject3.getText(),
            subject4.getText(),
            subject5.getText(),
            subject6.getText(),
            subject7.getText(),
            subject8.getText(),
            subject9.getText(),
            subject10.getText()
        };

        JTextField[] marksArray = {
            marks1, marks2, marks3, marks4, marks5,
            marks6, marks7, marks8, marks9, marks10
        };
        JTextField[] oMarksArray = {
            oMarks, oMarks1, oMarks2, oMarks3, oMarks4,
            oMarks5, oMarks6, oMarks7, oMarks8, oMarks9
        };
        int[] totalMarks = new int[10];
        int[] obtainedMarks = new int[10];
        int total = 0;
        int obtainedTotal = 0;
        for (int i = 0; i < 10; i++) {
            String marks = marksArray[i].getText();
            String oMarks = oMarksArray[i].getText();
            totalMarks[i] = marks.isEmpty() ? 0 : Integer.parseInt(marks);
            obtainedMarks[i] = oMarks.isEmpty() ? 0 : Integer.parseInt(oMarks);
            total += totalMarks[i];
            obtainedTotal += obtainedMarks[i];
        }
        int percentage = (obtainedTotal * 100) / total;
        // Create Result object
        resultFunctions result = new resultFunctions();
        result.setStudentRollNo(rollNo);
        result.setStudentClassId(className);
        result.setSubject1Name(subjectNames[0]);
        result.setSubject1TotalMarks(totalMarks[0]);
        result.setSubject1ObtainedMarks(obtainedMarks[0]);
        result.setSubject2Name(subjectNames[1]);
        result.setSubject2TotalMarks(totalMarks[1]);
        result.setSubject2ObtainedMarks(obtainedMarks[1]);
        result.setSubject3Name(subjectNames[2]);
        result.setSubject3TotalMarks(totalMarks[2]);
        result.setSubject3ObtainedMarks(obtainedMarks[2]);
        result.setSubject4Name(subjectNames[3]);
        result.setSubject4TotalMarks(totalMarks[3]);
        result.setSubject4ObtainedMarks(obtainedMarks[3]);
        result.setSubject5Name(subjectNames[4]);
        result.setSubject5TotalMarks(totalMarks[4]);
        result.setSubject5ObtainedMarks(obtainedMarks[4]);
        result.setSubject6Name(subjectNames[5]);
        result.setSubject6TotalMarks(totalMarks[5]);
        result.setSubject6ObtainedMarks(obtainedMarks[5]);
        result.setSubject7Name(subjectNames[6]);
        result.setSubject7TotalMarks(totalMarks[6]);
        result.setSubject7ObtainedMarks(obtainedMarks[6]);
        result.setSubject8Name(subjectNames[7]);
        result.setSubject8TotalMarks(totalMarks[7]);
        result.setSubject8ObtainedMarks(obtainedMarks[7]);
        result.setSubject9Name(subjectNames[8]);
        result.setSubject9TotalMarks(totalMarks[8]);
        result.setSubject9ObtainedMarks(obtainedMarks[8]);
        result.setSubject10Name(subjectNames[9]);
        result.setSubject10TotalMarks(totalMarks[9]);
        result.setSubject10ObtainedMarks(obtainedMarks[9]);
        String test = getTest.getText();
        result.setTestType(test);
        result.setResultId(Result);
        result.setTotalMarks(total);
        result.setObtainedMarks(obtainedTotal);
        result.setObtainedPercentage(percentage);

        // Call insertResult function
        result.insertResult(result);
    }//GEN-LAST:event_addResultMouseClicked

    private void marks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks1ActionPerformed

    private void subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject1ActionPerformed

    private void getClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getClassActionPerformed

    }//GEN-LAST:event_getClassActionPerformed

    private void getRollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getRollNoActionPerformed

    private void oMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarksActionPerformed

    private void getTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getTestActionPerformed

    private void oMarks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarks1ActionPerformed

    private void marks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks2ActionPerformed

    private void subject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject2ActionPerformed

    private void oMarks2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarks2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarks2ActionPerformed

    private void marks3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks3ActionPerformed

    private void subject3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject3ActionPerformed

    private void oMarks3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarks3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarks3ActionPerformed

    private void marks4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks4ActionPerformed

    private void subject4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject4ActionPerformed

    private void oMarks4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarks4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarks4ActionPerformed

    private void marks5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks5ActionPerformed

    private void subject5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject5ActionPerformed

    private void oMarks5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarks5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarks5ActionPerformed

    private void marks6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks6ActionPerformed

    private void subject6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject6ActionPerformed

    private void oMarks6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarks6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarks6ActionPerformed

    private void marks7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks7ActionPerformed

    private void subject7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject7ActionPerformed

    private void oMarks7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarks7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarks7ActionPerformed

    private void marks8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks8ActionPerformed

    private void subject8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject8ActionPerformed

    private void oMarks8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarks8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarks8ActionPerformed

    private void marks9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks9ActionPerformed

    private void subject9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject9ActionPerformed

    private void oMarks9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oMarks9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oMarks9ActionPerformed

    private void marks10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks10ActionPerformed

    private void subject10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject10ActionPerformed

    private void resultIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultIdActionPerformed
    resultFunctions obj = new resultFunctions();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addResultSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addResultSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addResultSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addResultSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addResultSubjects().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addResult;
    private javax.swing.JComboBox<String> getClass;
    private javax.swing.JTextField getRollNo;
    private javax.swing.JTextField getTest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField marks1;
    private javax.swing.JTextField marks10;
    private javax.swing.JTextField marks2;
    private javax.swing.JTextField marks3;
    private javax.swing.JTextField marks4;
    private javax.swing.JTextField marks5;
    private javax.swing.JTextField marks6;
    private javax.swing.JTextField marks7;
    private javax.swing.JTextField marks8;
    private javax.swing.JTextField marks9;
    private javax.swing.JTextField oMarks;
    private javax.swing.JTextField oMarks1;
    private javax.swing.JTextField oMarks2;
    private javax.swing.JTextField oMarks3;
    private javax.swing.JTextField oMarks4;
    private javax.swing.JTextField oMarks5;
    private javax.swing.JTextField oMarks6;
    private javax.swing.JTextField oMarks7;
    private javax.swing.JTextField oMarks8;
    private javax.swing.JTextField oMarks9;
    private javax.swing.JTextField resultId;
    private javax.swing.JLabel rollNo;
    private javax.swing.JTextField subject1;
    private javax.swing.JTextField subject10;
    private javax.swing.JTextField subject2;
    private javax.swing.JTextField subject3;
    private javax.swing.JTextField subject4;
    private javax.swing.JTextField subject5;
    private javax.swing.JTextField subject6;
    private javax.swing.JTextField subject7;
    private javax.swing.JTextField subject8;
    private javax.swing.JTextField subject9;
    // End of variables declaration//GEN-END:variables
}
