/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.school;

import java.sql.Connection;
import javax.swing.JFrame;

/**
 *
 * @author Taha Rasheed
 */
public class feeFrame extends javax.swing.JFrame {

    /**
     * Creates new form feeFrame
     */
    public feeFrame() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        addFeeBtn = new javax.swing.JButton();
        editFeeBtn = new javax.swing.JButton();
        payFeebtn = new javax.swing.JButton();
        thatHaveNotPaid = new javax.swing.JButton();
        payFeebtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(33, 37, 41));
        jPanel2.setForeground(new java.awt.Color(33, 37, 41));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(99, 230, 190));
        jLabel1.setText("Fee");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(648, 513));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(33, 37, 41));

        addFeeBtn.setBackground(new java.awt.Color(99, 230, 190));
        addFeeBtn.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        addFeeBtn.setForeground(new java.awt.Color(33, 37, 41));
        addFeeBtn.setText("Add Fee of Student");
        addFeeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 126, 214), 3, true));
        addFeeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFeeBtnMouseClicked(evt);
            }
        });
        addFeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFeeBtnActionPerformed(evt);
            }
        });

        editFeeBtn.setBackground(new java.awt.Color(99, 230, 190));
        editFeeBtn.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        editFeeBtn.setForeground(new java.awt.Color(33, 37, 41));
        editFeeBtn.setText("Edit Fee of Student");
        editFeeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 126, 214), 3, true));
        editFeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFeeBtnActionPerformed(evt);
            }
        });

        payFeebtn.setBackground(new java.awt.Color(99, 230, 190));
        payFeebtn.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        payFeebtn.setForeground(new java.awt.Color(33, 37, 41));
        payFeebtn.setText("Pay Fee");
        payFeebtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 126, 214), 3, true));
        payFeebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payFeebtnActionPerformed(evt);
            }
        });

        thatHaveNotPaid.setBackground(new java.awt.Color(99, 230, 190));
        thatHaveNotPaid.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        thatHaveNotPaid.setForeground(new java.awt.Color(33, 37, 41));
        thatHaveNotPaid.setText("Paid");
        thatHaveNotPaid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 126, 214), 3, true));
        thatHaveNotPaid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thatHaveNotPaidMouseClicked(evt);
            }
        });
        thatHaveNotPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thatHaveNotPaidActionPerformed(evt);
            }
        });

        payFeebtn1.setBackground(new java.awt.Color(99, 230, 190));
        payFeebtn1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        payFeebtn1.setForeground(new java.awt.Color(33, 37, 41));
        payFeebtn1.setText("Print Fee");
        payFeebtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 126, 214), 3, true));
        payFeebtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payFeebtn1MouseClicked(evt);
            }
        });
        payFeebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payFeebtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(editFeeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payFeebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thatHaveNotPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addFeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payFeebtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(addFeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(editFeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(payFeebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(thatHaveNotPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(payFeebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        jLabel2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+"\\src\\main\\java\\com\\mycompany\\Images\\im.png"));
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -70, 650, 610));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFeeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFeeBtnMouseClicked
        addFeeFrame addFee = new addFeeFrame();
        addFee.show();// TODO add your handling code here:
    }//GEN-LAST:event_addFeeBtnMouseClicked

    private void addFeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFeeBtnActionPerformed

    }//GEN-LAST:event_addFeeBtnActionPerformed

    private void editFeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFeeBtnActionPerformed
        editFeeFrame editFee = new editFeeFrame();
        editFee.show();// TODO add your handling code here:
    }//GEN-LAST:event_editFeeBtnActionPerformed

    private void payFeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payFeebtnActionPerformed
        payFeeFrame payFee = new payFeeFrame();
        payFee.show();
    }//GEN-LAST:event_payFeebtnActionPerformed

    private void thatHaveNotPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thatHaveNotPaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thatHaveNotPaidActionPerformed

    private void thatHaveNotPaidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thatHaveNotPaidMouseClicked
        FeeInfoFrame obj = new FeeInfoFrame();
        obj.setVisible(true);
    }//GEN-LAST:event_thatHaveNotPaidMouseClicked

    private void payFeebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payFeebtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payFeebtn1ActionPerformed

    private void payFeebtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payFeebtn1MouseClicked
        Connection con = ConnectionClass.db();
        FeeReceiptGenerator obj = new FeeReceiptGenerator(con);
        obj.setVisible(true);
        
    }//GEN-LAST:event_payFeebtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFeeBtn;
    private javax.swing.JButton editFeeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton payFeebtn;
    private javax.swing.JButton payFeebtn1;
    private javax.swing.JButton thatHaveNotPaid;
    // End of variables declaration//GEN-END:variables
}
